// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace mockup {
    
    
    public partial class BugDescription {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Table table1;
        
        private Gtk.Label label1;
        
        private Gtk.Entry txtSummary;
        
        private Gtk.Label lblDescription;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget mockup.BugDescription
            Stetic.BinContainer.Attach(this);
            this.Name = "mockup.BugDescription";
            // Container child mockup.BugDescription.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(1)), ((uint)(2)), false);
            this.table1.Name = "table1";
            // Container child table1.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Summary:");
            this.table1.Add(this.label1);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.label1]));
            w1.XOptions = ((Gtk.AttachOptions)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.txtSummary = new Gtk.Entry();
            this.txtSummary.CanFocus = true;
            this.txtSummary.Name = "txtSummary";
            this.txtSummary.IsEditable = true;
            this.txtSummary.InvisibleChar = '●';
            this.table1.Add(this.txtSummary);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.txtSummary]));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox2.Add(this.table1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.table1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.lblDescription = new Gtk.Label();
            this.lblDescription.Name = "lblDescription";
            this.lblDescription.Xalign = 0F;
            this.lblDescription.LabelProp = "";
            this.lblDescription.Wrap = true;
            this.vbox2.Add(this.lblDescription);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox2[this.lblDescription]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
