// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace mockup.Widgets {
    
    
    public partial class Detail {
        
        private Gtk.VBox vbox3;
        
        private Gtk.Table table2;
        
        private Gtk.Entry entry4;
        
        private Gtk.Entry entry5;
        
        private Gtk.Entry entry6;
        
        private Gtk.Label label4;
        
        private Gtk.HButtonBox hbuttonbox5;
        
        private Gtk.Button button25;
        
        private Gtk.Button button26;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget mockup.Widgets.Detail
            Stetic.BinContainer.Attach(this);
            this.Name = "mockup.Widgets.Detail";
            // Container child mockup.Widgets.Detail.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.table2 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(6));
            // Container child table2.Gtk.Table+TableChild
            this.entry4 = new Gtk.Entry();
            this.entry4.CanFocus = true;
            this.entry4.Name = "entry4";
            this.entry4.IsEditable = true;
            this.entry4.InvisibleChar = '●';
            this.table2.Add(this.entry4);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table2[this.entry4]));
            w1.LeftAttach = ((uint)(1));
            w1.RightAttach = ((uint)(2));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.entry5 = new Gtk.Entry();
            this.entry5.CanFocus = true;
            this.entry5.Name = "entry5";
            this.entry5.IsEditable = true;
            this.entry5.InvisibleChar = '●';
            this.table2.Add(this.entry5);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table2[this.entry5]));
            w2.TopAttach = ((uint)(1));
            w2.BottomAttach = ((uint)(2));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.entry6 = new Gtk.Entry();
            this.entry6.CanFocus = true;
            this.entry6.Name = "entry6";
            this.entry6.IsEditable = true;
            this.entry6.InvisibleChar = '●';
            this.table2.Add(this.entry6);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table2[this.entry6]));
            w3.TopAttach = ((uint)(2));
            w3.BottomAttach = ((uint)(3));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("label4");
            this.table2.Add(this.label4);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table2[this.label4]));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox3.Add(this.table2);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox3[this.table2]));
            w5.Position = 0;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbuttonbox5 = new Gtk.HButtonBox();
            this.hbuttonbox5.Name = "hbuttonbox5";
            this.hbuttonbox5.Spacing = 6;
            this.hbuttonbox5.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
            this.button25 = new Gtk.Button();
            this.button25.CanFocus = true;
            this.button25.Name = "button25";
            this.button25.UseUnderline = true;
            this.button25.Label = Mono.Unix.Catalog.GetString("button25");
            this.hbuttonbox5.Add(this.button25);
            Gtk.ButtonBox.ButtonBoxChild w6 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5[this.button25]));
            w6.Expand = false;
            w6.Fill = false;
            // Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
            this.button26 = new Gtk.Button();
            this.button26.CanFocus = true;
            this.button26.Name = "button26";
            this.button26.UseUnderline = true;
            this.button26.Label = Mono.Unix.Catalog.GetString("button26");
            this.hbuttonbox5.Add(this.button26);
            Gtk.ButtonBox.ButtonBoxChild w7 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5[this.button26]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            this.vbox3.Add(this.hbuttonbox5);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbuttonbox5]));
            w8.Position = 1;
            w8.Expand = false;
            w8.Fill = false;
            this.Add(this.vbox3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
