// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace mockup.Widgets {
    
    
    public partial class Search {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Table table1;
        
        private Gtk.Entry entry2;
        
        private Gtk.Entry entry3;
        
        private Gtk.Label label1;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.Entry txtEmail;
        
        private Gtk.HButtonBox hbuttonbox4;
        
        private Gtk.Button cmdClear;
        
        private Gtk.Button cmdSearch;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget mockup.Widgets.Search
            Stetic.BinContainer.Attach(this);
            this.Name = "mockup.Widgets.Search";
            // Container child mockup.Widgets.Search.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.entry2 = new Gtk.Entry();
            this.entry2.CanFocus = true;
            this.entry2.Name = "entry2";
            this.entry2.IsEditable = true;
            this.entry2.InvisibleChar = '●';
            this.table1.Add(this.entry2);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.entry2]));
            w1.TopAttach = ((uint)(1));
            w1.BottomAttach = ((uint)(2));
            w1.LeftAttach = ((uint)(1));
            w1.RightAttach = ((uint)(2));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.entry3 = new Gtk.Entry();
            this.entry3.CanFocus = true;
            this.entry3.Name = "entry3";
            this.entry3.IsEditable = true;
            this.entry3.InvisibleChar = '●';
            this.table1.Add(this.entry3);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.entry3]));
            w2.TopAttach = ((uint)(2));
            w2.BottomAttach = ((uint)(3));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Email");
            this.table1.Add(this.label1);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.label1]));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("label2");
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w4.TopAttach = ((uint)(1));
            w4.BottomAttach = ((uint)(2));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("label3");
            this.table1.Add(this.label3);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
            w5.TopAttach = ((uint)(2));
            w5.BottomAttach = ((uint)(3));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.txtEmail = new Gtk.Entry();
            this.txtEmail.CanFocus = true;
            this.txtEmail.Name = "txtEmail";
            this.txtEmail.IsEditable = true;
            this.txtEmail.InvisibleChar = '●';
            this.table1.Add(this.txtEmail);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.txtEmail]));
            w6.LeftAttach = ((uint)(1));
            w6.RightAttach = ((uint)(2));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox2.Add(this.table1);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox2[this.table1]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbuttonbox4 = new Gtk.HButtonBox();
            this.hbuttonbox4.Name = "hbuttonbox4";
            this.hbuttonbox4.Spacing = 6;
            this.hbuttonbox4.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
            this.cmdClear = new Gtk.Button();
            this.cmdClear.CanFocus = true;
            this.cmdClear.Name = "cmdClear";
            this.cmdClear.UseUnderline = true;
            this.cmdClear.Label = Mono.Unix.Catalog.GetString("Clear");
            this.hbuttonbox4.Add(this.cmdClear);
            Gtk.ButtonBox.ButtonBoxChild w8 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4[this.cmdClear]));
            w8.Expand = false;
            w8.Fill = false;
            // Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
            this.cmdSearch = new Gtk.Button();
            this.cmdSearch.CanFocus = true;
            this.cmdSearch.Name = "cmdSearch";
            this.cmdSearch.UseUnderline = true;
            this.cmdSearch.Label = Mono.Unix.Catalog.GetString("Search");
            this.hbuttonbox4.Add(this.cmdSearch);
            Gtk.ButtonBox.ButtonBoxChild w9 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4[this.cmdSearch]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            this.vbox2.Add(this.hbuttonbox4);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbuttonbox4]));
            w10.Position = 1;
            w10.Expand = false;
            w10.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.cmdClear.Clicked += new System.EventHandler(this.OnClear);
            this.cmdSearch.Clicked += new System.EventHandler(this.OnSearch);
        }
    }
}
