// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace mockup {
    
    
    public partial class BugList {
        
        private Gtk.ScrolledWindow scrolledwindow3;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget mockup.BugList
            Stetic.BinContainer.Attach(this);
            this.Name = "mockup.BugList";
            // Container child mockup.BugList.Gtk.Container+ContainerChild
            this.scrolledwindow3 = new Gtk.ScrolledWindow();
            this.scrolledwindow3.CanFocus = true;
            this.scrolledwindow3.Name = "scrolledwindow3";
            this.scrolledwindow3.ShadowType = ((Gtk.ShadowType)(1));
            this.Add(this.scrolledwindow3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
