// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace mockup {
    
    
    public partial class BugComment {
        
        private Gtk.VBox vbox5;
        
        private Gtk.Table table6;
        
        private Gtk.Label label11;
        
        private Gtk.Label label7;
        
        private Gtk.Label label9;
        
        private Gtk.Label lblDate;
        
        private Gtk.Label lblID;
        
        private Gtk.Label lblName;
        
        private Gtk.Label lblText;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget mockup.BugComment
            Stetic.BinContainer.Attach(this);
            this.Name = "mockup.BugComment";
            // Container child mockup.BugComment.Gtk.Container+ContainerChild
            this.vbox5 = new Gtk.VBox();
            this.vbox5.Name = "vbox5";
            this.vbox5.Spacing = 6;
            // Container child vbox5.Gtk.Box+BoxChild
            this.table6 = new Gtk.Table(((uint)(1)), ((uint)(6)), false);
            this.table6.Name = "table6";
            // Container child table6.Gtk.Table+TableChild
            this.label11 = new Gtk.Label();
            this.label11.Name = "label11";
            this.label11.Xalign = 0F;
            this.label11.LabelProp = Mono.Unix.Catalog.GetString("on");
            this.table6.Add(this.label11);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table6[this.label11]));
            w1.LeftAttach = ((uint)(4));
            w1.RightAttach = ((uint)(5));
            w1.XOptions = ((Gtk.AttachOptions)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table6.Gtk.Table+TableChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.Xalign = 0F;
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("Comment #");
            this.table6.Add(this.label7);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table6[this.label7]));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table6.Gtk.Table+TableChild
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.Xalign = 0F;
            this.label9.LabelProp = Mono.Unix.Catalog.GetString("from");
            this.table6.Add(this.label9);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table6[this.label9]));
            w3.LeftAttach = ((uint)(2));
            w3.RightAttach = ((uint)(3));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table6.Gtk.Table+TableChild
            this.lblDate = new Gtk.Label();
            this.lblDate.Name = "lblDate";
            this.lblDate.Xalign = 0F;
            this.lblDate.LabelProp = "";
            this.table6.Add(this.lblDate);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table6[this.lblDate]));
            w4.LeftAttach = ((uint)(5));
            w4.RightAttach = ((uint)(6));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table6.Gtk.Table+TableChild
            this.lblID = new Gtk.Label();
            this.lblID.Name = "lblID";
            this.lblID.Xalign = 0F;
            this.lblID.LabelProp = "";
            this.table6.Add(this.lblID);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table6[this.lblID]));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table6.Gtk.Table+TableChild
            this.lblName = new Gtk.Label();
            this.lblName.Name = "lblName";
            this.lblName.Xalign = 0F;
            this.lblName.LabelProp = "";
            this.table6.Add(this.lblName);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table6[this.lblName]));
            w6.LeftAttach = ((uint)(3));
            w6.RightAttach = ((uint)(4));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox5.Add(this.table6);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox5[this.table6]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.lblText = new Gtk.Label();
            this.lblText.Name = "lblText";
            this.lblText.Xalign = 0F;
            this.lblText.LabelProp = "";
            this.vbox5.Add(this.lblText);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox5[this.lblText]));
            w8.Position = 1;
            w8.Expand = false;
            w8.Fill = false;
            this.Add(this.vbox5);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
